apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`microk8s.ddns.net`)
      kind: Rule
      services:
        - name: whoami
          port: 80
