additionalArguments:
  - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=azure
  - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
env:
  - name: AZURE_CLIENT_ID
    value: ''
  - name: AZURE_CLIENT_SECRET
    value: ''
  - name: AZURE_SUBSCRIPTION_ID
    value: ''
  - name: AZURE_TENANT_ID
    value: ''
  - name: AZURE_RESOURCE_GROUP
    value: ''
