---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013: false
MD024: true
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed punctuation in headers
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD034: false                  # Allow bare urls
MD036: false                  # Emphasis used instead of a heading
MD040: false                  # No language-specific fenced code blocks

#################
# Rules by tags #
#################
blank_lines: false            # Error on blank lines
